### ISSUE TITLE
Fix server crashing due to i18n/React.Suspense

### ISSUE THREAD

**Issue by kyle-flynn** [orange-alliance/toa-react#26]
Our localization efforts are fantastic.

However, we need to do a little work to make this work on the server. I experimented and troubleshooted to find out what _exactly_ is the issue.

I did a client-side check that makes `window` undefined in our `i18n.ts` for the server. When I test with that change, this is the stracktrace that occurs:

```
(node:6940) UnhandledPromiseRejectionWarning: Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.t.render (Z:\Coding\Repositories\toa-react\build\index.js:2:731528)
    at e.t.read (Z:\Coding\Repositories\toa-react\build\index.js:2:730558)
    at Object.renderToString (Z:\Coding\Repositories\toa-react\build\index.js:2:736159)
    at Object.<anonymous> (Z:\Coding\Repositories\toa-react\build\index.js:2:709571)
    at Generator.next (<anonymous>)
    at o (Z:\Coding\Repositories\toa-react\build\index.js:2:707905)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://github.com/gatsbyjs/gatsby/issues/20371 may be related

**Comment by kyle-flynn** [comment]
I got the application building again by removing the use of `React.Suspense` in `HomePage.tsx` line 114. However, translations aren't working anymore. I'll be looking into adding it on the server.
